---
- hosts: Danforth_Shakoor
  remote_user: pi
  become: yes
  vars:
    timeout: 30
  tasks:
    - name: Transfer local interfaces to /etc/network/interfaces to the Raspberry PIs.
      copy:
        src=/home/clizarraga/Projects/ESPCOR_Bramble_GH9C/pi_config/interfaces
        dest=/etc/network/interfaces

    - name: Reboot PIs
      shell: /sbin/reboot
      async: 1
      poll: 0
      ignore_errors: True
      
      
      
